package entity;

import java.util.Date;

public class Announcement {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announcement_id
     *
     * @mbg.generated
     */
    private Integer announcementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announcement_time
     *
     * @mbg.generated
     */
    private Date announcementTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announcement_title
     *
     * @mbg.generated
     */
    private String announcementTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announcement_content
     *
     * @mbg.generated
     */
    private String announcementContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announcement_id
     *
     * @return the value of announcement.announcement_id
     * @mbg.generated
     */
    public Integer getAnnouncementId() {
        return announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announcement_id
     *
     * @param announcementId the value for announcement.announcement_id
     * @mbg.generated
     */
    public void setAnnouncementId(Integer announcementId) {
        this.announcementId = announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.course_id
     *
     * @return the value of announcement.course_id
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.course_id
     *
     * @param courseId the value for announcement.course_id
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announcement_time
     *
     * @return the value of announcement.announcement_time
     * @mbg.generated
     */
    public Date getAnnouncementTime() {
        return announcementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announcement_time
     *
     * @param announcementTime the value for announcement.announcement_time
     * @mbg.generated
     */
    public void setAnnouncementTime(Date announcementTime) {
        this.announcementTime = announcementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announcement_title
     *
     * @return the value of announcement.announcement_title
     * @mbg.generated
     */
    public String getAnnouncementTitle() {
        return announcementTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announcement_title
     *
     * @param announcementTitle the value for announcement.announcement_title
     * @mbg.generated
     */
    public void setAnnouncementTitle(String announcementTitle) {
        this.announcementTitle = announcementTitle == null ? null : announcementTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announcement_content
     *
     * @return the value of announcement.announcement_content
     * @mbg.generated
     */
    public String getAnnouncementContent() {
        return announcementContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announcement_content
     *
     * @param announcementContent the value for announcement.announcement_content
     * @mbg.generated
     */
    public void setAnnouncementContent(String announcementContent) {
        this.announcementContent = announcementContent == null ? null : announcementContent.trim();
    }
}