package entity;

public class CourseResourceEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_resource.course_resource_id
     *
     * @mbg.generated
     */
    private Integer courseResourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_resource.course_resource_path
     *
     * @mbg.generated
     */
    private String courseResourcePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_resource.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_resource.course_resource_filename
     *
     * @mbg.generated
     */
    private String courseResourceFilename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_resource.course_resource_id
     *
     * @return the value of course_resource.course_resource_id
     *
     * @mbg.generated
     */
    public Integer getCourseResourceId() {
        return courseResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_resource.course_resource_id
     *
     * @param courseResourceId the value for course_resource.course_resource_id
     *
     * @mbg.generated
     */
    public void setCourseResourceId(Integer courseResourceId) {
        this.courseResourceId = courseResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_resource.course_resource_path
     *
     * @return the value of course_resource.course_resource_path
     *
     * @mbg.generated
     */
    public String getCourseResourcePath() {
        return courseResourcePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_resource.course_resource_path
     *
     * @param courseResourcePath the value for course_resource.course_resource_path
     *
     * @mbg.generated
     */
    public void setCourseResourcePath(String courseResourcePath) {
        this.courseResourcePath = courseResourcePath == null ? null : courseResourcePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_resource.course_id
     *
     * @return the value of course_resource.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_resource.course_id
     *
     * @param courseId the value for course_resource.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_resource.course_resource_filename
     *
     * @return the value of course_resource.course_resource_filename
     *
     * @mbg.generated
     */
    public String getCourseResourceFilename() {
        return courseResourceFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_resource.course_resource_filename
     *
     * @param courseResourceFilename the value for course_resource.course_resource_filename
     *
     * @mbg.generated
     */
    public void setCourseResourceFilename(String courseResourceFilename) {
        this.courseResourceFilename = courseResourceFilename == null ? null : courseResourceFilename.trim();
    }
}