package entity;

import vo.AddJobVO;
import vo.UpdateJobVO;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class JobEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_id
     *
     * @mbg.generated
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_title
     *
     * @mbg.generated
     */
    private String jobTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_content
     *
     * @mbg.generated
     */
    private String jobContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_begin_time
     *
     * @mbg.generated
     */
    private Date jobBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_end_time
     *
     * @mbg.generated
     */
    private Date jobEndTime;

    public JobEntity() {
    }

    public JobEntity(UpdateJobVO updateJobVO) throws ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        this.jobId = updateJobVO.getJobId();
        this.jobTitle = updateJobVO.getJobTitle();
        this.jobContent = updateJobVO.getJobContent();
        this.jobBeginTime = sdf.parse(updateJobVO.getJobBeginTime());
        this.jobEndTime = sdf.parse(updateJobVO.getJobEndTime());
    }
    public JobEntity(AddJobVO addJobVO) {
        this.courseId = addJobVO.getCourseId();
        this.jobTitle = addJobVO.getJobTitle();
        this.jobContent = addJobVO.getJobContent();
        this.jobBeginTime = addJobVO.getJobBeginTime();
        this.jobEndTime = addJobVO.getJobEndTime();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_id
     *
     * @return the value of job.job_id
     * @mbg.generated
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_id
     *
     * @param jobId the value for job.job_id
     * @mbg.generated
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.course_id
     *
     * @return the value of job.course_id
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.course_id
     *
     * @param courseId the value for job.course_id
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_title
     *
     * @return the value of job.job_title
     * @mbg.generated
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_title
     *
     * @param jobTitle the value for job.job_title
     * @mbg.generated
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_content
     *
     * @return the value of job.job_content
     * @mbg.generated
     */
    public String getJobContent() {
        return jobContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_content
     *
     * @param jobContent the value for job.job_content
     * @mbg.generated
     */
    public void setJobContent(String jobContent) {
        this.jobContent = jobContent == null ? null : jobContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_begin_time
     *
     * @return the value of job.job_begin_time
     * @mbg.generated
     */
    public Date getJobBeginTime() {
        return jobBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_begin_time
     *
     * @param jobBeginTime the value for job.job_begin_time
     * @mbg.generated
     */
    public void setJobBeginTime(Date jobBeginTime) {
        this.jobBeginTime = jobBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_end_time
     *
     * @return the value of job.job_end_time
     * @mbg.generated
     */
    public Date getJobEndTime() {
        return jobEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_end_time
     *
     * @param jobEndTime the value for job.job_end_time
     * @mbg.generated
     */
    public void setJobEndTime(Date jobEndTime) {
        this.jobEndTime = jobEndTime;
    }

    @Override
    public String toString() {
        return "JobEntity{" +
                "jobId=" + jobId +
                ", courseId=" + courseId +
                ", jobTitle='" + jobTitle + '\'' +
                ", jobContent='" + jobContent + '\'' +
                ", jobBeginTime=" + jobBeginTime +
                ", jobEndTime=" + jobEndTime +
                '}';
    }
}