package entity;

import java.util.Date;

public class JobSubmitItemEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit_item.job_submit_item_id
     *
     * @mbg.generated
     */
    private Integer jobSubmitItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit_item.job_id
     *
     * @mbg.generated
     */
    private Integer jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit_item.job_submit_item_filename
     *
     * @mbg.generated
     */
    private String jobSubmitItemFilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit_item.user_id
     *
     * @mbg.generated
     */
    private int  userId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit_item.job_submit_time
     *
     * @mbg.generated
     */
    private Date jobSubmitTime;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit_item.job_submit_time
     *
     * @return the value of job_submit_item.job_submit_time
     *
     * @mbg.generated
     */
    public Date getJobSubmitTime() {
        return jobSubmitTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit_item.job_submit_item_id
     *
     * @param jobSubmitTime the value for job_submit_item.job_submit_time
     *
     * @mbg.generated
     */
    public void setJobSubmitTime(Date jobSubmitTime) {
        this.jobSubmitTime = jobSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit_item.job_submit_item_id
     *
     * @return the value of job_submit_item.job_submit_item_id
     *
     * @mbg.generated
     */
    public Integer getJobSubmitItemId() {
        return jobSubmitItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit_item.job_submit_item_id
     *
     * @param jobSubmitItemId the value for job_submit_item.job_submit_item_id
     *
     * @mbg.generated
     */
    public void setJobSubmitItemId(Integer jobSubmitItemId) {
        this.jobSubmitItemId = jobSubmitItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit_item.job_id
     *
     * @return the value of job_submit_item.job_id
     *
     * @mbg.generated
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit_item.job_id
     *
     * @param jobId the value for job_submit_item.job_id
     *
     * @mbg.generated
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit_item.job_submit_item_filename
     *
     * @return the value of job_submit_item.job_submit_item_filename
     *
     * @mbg.generated
     */
    public String getJobSubmitItemFilename() {
        return jobSubmitItemFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit_item.job_submit_item_filename
     *
     * @param jobSubmitItemFilename the value for job_submit_item.job_submit_item_filename
     *
     * @mbg.generated
     */
    public void setJobSubmitItemFilename(String jobSubmitItemFilename) {
        this.jobSubmitItemFilename = jobSubmitItemFilename == null ? null : jobSubmitItemFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit_item.user_id
     *
     * @return the value of job_submit_item.user_id
     *
     * @mbg.generated
     */
    public int getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit_item.user_id
     *
     * @param userId the value for job_submit_item.user_id
     *
     * @mbg.generated
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }
}