package entity;

public class JobSubmitItemEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit_item.job_submit_item_id
     *
     * @mbg.generated
     */
    private Integer jobSubmitItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit_item.job_id
     *
     * @mbg.generated
     */
    private Integer jobSubmitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit_item.job_submit_item_filename
     *
     * @mbg.generated
     */
    private String jobSubmitItemFilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit_item.job_submit_item_path
     *
     * @mbg.generated
     */
    private String jobSubmitItemPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit_item.job_submit_item_id
     *
     * @return the value of job_submit_item.job_submit_item_id
     *
     * @mbg.generated
     */
    public Integer getJobSubmitItemId() {
        return jobSubmitItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit_item.job_submit_item_id
     *
     * @param jobSubmitItemId the value for job_submit_item.job_submit_item_id
     *
     * @mbg.generated
     */
    public void setJobSubmitItemId(Integer jobSubmitItemId) {
        this.jobSubmitItemId = jobSubmitItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit_item.job_submit_id
     *
     * @return the value of job_submit_item.job_submit_id
     *
     * @mbg.generated
     */
    public Integer getJobSubmitId() {
        return jobSubmitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit_item.job_submit_id
     *
     * @param jobSubmitId the value for job_submit_item.job_submit_id
     *
     * @mbg.generated
     */
    public void setJobSubmitId(Integer jobSubmitId) {
        this.jobSubmitId = jobSubmitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit_item.job_submit_item_filename
     *
     * @return the value of job_submit_item.job_submit_item_filename
     *
     * @mbg.generated
     */
    public String getJobSubmitItemFilename() {
        return jobSubmitItemFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit_item.job_submit_item_filename
     *
     * @param jobSubmitItemFilename the value for job_submit_item.job_submit_item_filename
     *
     * @mbg.generated
     */
    public void setJobSubmitItemFilename(String jobSubmitItemFilename) {
        this.jobSubmitItemFilename = jobSubmitItemFilename == null ? null : jobSubmitItemFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit_item.job_submit_item_path
     *
     * @return the value of job_submit_item.job_submit_item_path
     *
     * @mbg.generated
     */
    public String getJobSubmitItemPath() {
        return jobSubmitItemPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit_item.job_submit_item_path
     *
     * @param jobSubmitItemPath the value for job_submit_item.job_submit_item_path
     *
     * @mbg.generated
     */
    public void setJobSubmitItemPath(String jobSubmitItemPath) {
        this.jobSubmitItemPath = jobSubmitItemPath == null ? null : jobSubmitItemPath.trim();
    }
}