package entity;

import java.util.Date;

public class JobSubmit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit.job_submit_id
     *
     * @mbg.generated
     */
    private Integer jobSubmitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit.task_id
     *
     * @mbg.generated
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_submit. job_submit_time
     *
     * @mbg.generated
     */
    private Date jobSubmitTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit.job_submit_id
     *
     * @return the value of job_submit.job_submit_id
     *
     * @mbg.generated
     */
    public Integer getJobSubmitId() {
        return jobSubmitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit.job_submit_id
     *
     * @param jobSubmitId the value for job_submit.job_submit_id
     *
     * @mbg.generated
     */
    public void setJobSubmitId(Integer jobSubmitId) {
        this.jobSubmitId = jobSubmitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit.task_id
     *
     * @return the value of job_submit.task_id
     *
     * @mbg.generated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit.task_id
     *
     * @param taskId the value for job_submit.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit.user_id
     *
     * @return the value of job_submit.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit.user_id
     *
     * @param userId the value for job_submit.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_submit. job_submit_time
     *
     * @return the value of job_submit. job_submit_time
     *
     * @mbg.generated
     */
    public Date getJobSubmitTime() {
        return jobSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_submit. job_submit_time
     *
     * @param jobSubmitTime the value for job_submit. job_submit_time
     *
     * @mbg.generated
     */
    public void setJobSubmitTime(Date jobSubmitTime) {
        this.jobSubmitTime = jobSubmitTime;
    }
}