package entity;

import java.util.Date;

public class Notify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.notify_id
     *
     * @mbg.generated
     */
    private Integer notifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.notify_content
     *
     * @mbg.generated
     */
    private String notifyContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.notify_time
     *
     * @mbg.generated
     */
    private Date notifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.notify_producer
     *
     * @mbg.generated
     */
    private Integer notifyProducer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify.notify_type
     *
     * @mbg.generated
     */
    private String notifyType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.notify_id
     *
     * @return the value of notify.notify_id
     *
     * @mbg.generated
     */
    public Integer getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.notify_id
     *
     * @param notifyId the value for notify.notify_id
     *
     * @mbg.generated
     */
    public void setNotifyId(Integer notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.notify_content
     *
     * @return the value of notify.notify_content
     *
     * @mbg.generated
     */
    public String getNotifyContent() {
        return notifyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.notify_content
     *
     * @param notifyContent the value for notify.notify_content
     *
     * @mbg.generated
     */
    public void setNotifyContent(String notifyContent) {
        this.notifyContent = notifyContent == null ? null : notifyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.notify_time
     *
     * @return the value of notify.notify_time
     *
     * @mbg.generated
     */
    public Date getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.notify_time
     *
     * @param notifyTime the value for notify.notify_time
     *
     * @mbg.generated
     */
    public void setNotifyTime(Date notifyTime) {
        this.notifyTime = notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.notify_producer
     *
     * @return the value of notify.notify_producer
     *
     * @mbg.generated
     */
    public Integer getNotifyProducer() {
        return notifyProducer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.notify_producer
     *
     * @param notifyProducer the value for notify.notify_producer
     *
     * @mbg.generated
     */
    public void setNotifyProducer(Integer notifyProducer) {
        this.notifyProducer = notifyProducer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify.notify_type
     *
     * @return the value of notify.notify_type
     *
     * @mbg.generated
     */
    public String getNotifyType() {
        return notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify.notify_type
     *
     * @param notifyType the value for notify.notify_type
     *
     * @mbg.generated
     */
    public void setNotifyType(String notifyType) {
        this.notifyType = notifyType == null ? null : notifyType.trim();
    }
}