package entity;

public class Qiniu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu.qiniu_id
     *
     * @mbg.generated
     */
    private Integer qiniuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu.sk
     *
     * @mbg.generated
     */
    private String sk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu.ak
     *
     * @mbg.generated
     */
    private String ak;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu.bucket
     *
     * @mbg.generated
     */
    private String bucket;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu.qiniu_id
     *
     * @return the value of qiniu.qiniu_id
     *
     * @mbg.generated
     */
    public Integer getQiniuId() {
        return qiniuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu.qiniu_id
     *
     * @param qiniuId the value for qiniu.qiniu_id
     *
     * @mbg.generated
     */
    public void setQiniuId(Integer qiniuId) {
        this.qiniuId = qiniuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu.username
     *
     * @return the value of qiniu.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu.username
     *
     * @param username the value for qiniu.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu.sk
     *
     * @return the value of qiniu.sk
     *
     * @mbg.generated
     */
    public String getSk() {
        return sk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu.sk
     *
     * @param sk the value for qiniu.sk
     *
     * @mbg.generated
     */
    public void setSk(String sk) {
        this.sk = sk == null ? null : sk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu.ak
     *
     * @return the value of qiniu.ak
     *
     * @mbg.generated
     */
    public String getAk() {
        return ak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu.ak
     *
     * @param ak the value for qiniu.ak
     *
     * @mbg.generated
     */
    public void setAk(String ak) {
        this.ak = ak == null ? null : ak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu.bucket
     *
     * @return the value of qiniu.bucket
     *
     * @mbg.generated
     */
    public String getBucket() {
        return bucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu.bucket
     *
     * @param bucket the value for qiniu.bucket
     *
     * @mbg.generated
     */
    public void setBucket(String bucket) {
        this.bucket = bucket == null ? null : bucket.trim();
    }
}