package entity;

public class StudentCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.student_course_id
     *
     * @mbg.generated
     */
    private Integer studentCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.student_id
     *
     * @mbg.generated
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.student_course_id
     *
     * @return the value of student_course.student_course_id
     *
     * @mbg.generated
     */
    public Integer getStudentCourseId() {
        return studentCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.student_course_id
     *
     * @param studentCourseId the value for student_course.student_course_id
     *
     * @mbg.generated
     */
    public void setStudentCourseId(Integer studentCourseId) {
        this.studentCourseId = studentCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.student_id
     *
     * @return the value of student_course.student_id
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.student_id
     *
     * @param studentId the value for student_course.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.course_id
     *
     * @return the value of student_course.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.course_id
     *
     * @param courseId the value for student_course.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}