package entity;

import java.util.Date;

public class UpvoteEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upvote.upvote_id
     *
     * @mbg.generated
     */
    private Integer upvoteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upvote.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upvote.comment_id
     *
     * @mbg.generated
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upvote.upvote_time
     *
     * @mbg.generated
     */
    private Date upvoteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upvote.upvote_id
     *
     * @return the value of upvote.upvote_id
     *
     * @mbg.generated
     */
    public Integer getUpvoteId() {
        return upvoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upvote.upvote_id
     *
     * @param upvoteId the value for upvote.upvote_id
     *
     * @mbg.generated
     */
    public void setUpvoteId(Integer upvoteId) {
        this.upvoteId = upvoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upvote.user_id
     *
     * @return the value of upvote.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upvote.user_id
     *
     * @param userId the value for upvote.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upvote.comment_id
     *
     * @return the value of upvote.comment_id
     *
     * @mbg.generated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upvote.comment_id
     *
     * @param commentId the value for upvote.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upvote.upvote_time
     *
     * @return the value of upvote.upvote_time
     *
     * @mbg.generated
     */
    public Date getUpvoteTime() {
        return upvoteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upvote.upvote_time
     *
     * @param upvoteTime the value for upvote.upvote_time
     *
     * @mbg.generated
     */
    public void setUpvoteTime(Date upvoteTime) {
        this.upvoteTime = upvoteTime;
    }
}