package entity;

public class UserNotifyEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notify.user_notify_id
     *
     * @mbg.generated
     */
    private Integer userNotifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notify.message_id
     *
     * @mbg.generated
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notify.receiver_id
     *
     * @mbg.generated
     */
    private Integer receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notify.is_read
     *
     * @mbg.generated
     */
    private Boolean isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notify.user_notify_id
     *
     * @return the value of user_notify.user_notify_id
     *
     * @mbg.generated
     */
    public Integer getUserNotifyId() {
        return userNotifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notify.user_notify_id
     *
     * @param userNotifyId the value for user_notify.user_notify_id
     *
     * @mbg.generated
     */
    public void setUserNotifyId(Integer userNotifyId) {
        this.userNotifyId = userNotifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notify.message_id
     *
     * @return the value of user_notify.message_id
     *
     * @mbg.generated
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notify.message_id
     *
     * @param messageId the value for user_notify.message_id
     *
     * @mbg.generated
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notify.receiver_id
     *
     * @return the value of user_notify.receiver_id
     *
     * @mbg.generated
     */
    public Integer getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notify.receiver_id
     *
     * @param receiverId the value for user_notify.receiver_id
     *
     * @mbg.generated
     */
    public void setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notify.is_read
     *
     * @return the value of user_notify.is_read
     *
     * @mbg.generated
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notify.is_read
     *
     * @param isRead the value for user_notify.is_read
     *
     * @mbg.generated
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }
}